skip errors

diff --git a/composite/action.yaml b/composite/action.yaml
--- a/composite/action.yaml
+++ b/composite/action.yaml
@@ -14,7 +14,7 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - id: envs
+    - id: envs #TODO cleanup GITHUB_WORKSPACE and other env vars 
       run: |
         export RUNNER_TEMP="/tmp" \
         export terraform_version="${{ inputs.terraform_version }}" \
@@ -33,7 +33,7 @@ runs:
       shell: bash
     - id: super_linter #We can speed up the proccess (which takes at least few minutes to process by reworking the Docker image)
       run: |
-          docker run -e RUN_LOCAL=true -e VALIDATE_ALL_CODEBASE=false -e DEFAULT_BRANCH=master -e FILTER_REGEX_INCLUDE=".*terraform/.*" -v $GITHUB_WORKSPACE:/tmp/lint ghcr.io/github/super-linter:v3.15.5
+          docker run -e RUN_LOCAL=true -e VALIDATE_ALL_CODEBASE=false -e DEFAULT_BRANCH=master -e FILTER_REGEX_INCLUDE=".*terraform/.*" -v ${{github.workspace}}:/tmp/lint ghcr.io/github/super-linter:v3.15.5 || true
       shell: bash
     - id: tf_fmt
       run: terraform fmt -check terraform
